
// --------------------------------------------------------
// Generated by glux perl script (Fri Dec  7 13:47:28 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Sat Dec  8 07:08:46 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Sat Dec  8 07:08:54 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Sat Dec  8 07:10:14 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Fri Dec 21 11:03:30 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Fri Dec 21 11:07:33 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Fri Dec 21 11:25:55 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Fri Jan  4 09:29:06 2013)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Thu Feb 14 17:17:07 2013)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Sat Sep  7 15:19:01 2013)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Fri Oct  4 19:23:21 2013)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Wed Dec 18 08:37:01 2013)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Wed Dec 18 08:37:09 2013)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Sat Jan  4 13:28:24 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Tue Jan  7 18:52:05 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Tue Jan  7 19:31:51 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Tue Jan 14 20:41:06 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Tue Feb 11 09:20:27 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Tue Feb 11 10:46:25 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Sun May 11 20:42:02 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Tue May 20 01:36:42 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Thu Jun 19 23:10:01 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Wed Jul 30 07:20:02 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Mon Feb 23 17:43:01 2015)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_apple_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap)
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
