
// --------------------------------------------------------
// Generated by glux perl script (Fri Dec  7 13:47:25 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Sat Dec  8 07:08:38 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Sat Dec  8 07:08:53 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Sat Dec  8 07:10:13 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Fri Dec 21 11:03:28 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Fri Dec 21 11:07:32 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Fri Dec 21 11:25:51 2012)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Fri Jan  4 09:25:11 2013)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Fri Jan  4 09:27:54 2013)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Thu Feb 14 17:16:55 2013)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Sat Sep  7 15:19:01 2013)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Fri Oct  4 19:23:19 2013)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Wed Dec 18 08:36:59 2013)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Wed Dec 18 08:37:08 2013)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Sat Jan  4 13:28:19 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Tue Jan  7 18:51:58 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Tue Jan  7 19:31:51 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Tue Jan 14 20:41:02 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Tue Feb 11 09:20:22 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Tue Feb 11 10:46:25 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Sun May 11 20:41:56 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Tue May 20 01:36:37 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Thu Jun 19 23:09:56 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Wed Jul 30 07:19:57 2014)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------

// --------------------------------------------------------
// Generated by glux perl script (Mon Feb 23 17:42:55 2015)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#ifdef WIN32
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#ifdef WIN32
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
#  include "glux_apple_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_vertex_array_range__
#define __GLUX_GL_APPLE_vertex_array_range__

GLUX_NEW_PLUGIN(GL_APPLE_vertex_array_range)
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_VERTEX_ARRAY_RANGE_APPLE
#  define GL_VERTEX_ARRAY_RANGE_APPLE 0x851D
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE
#  define GL_VERTEX_ARRAY_RANGE_LENGTH_APPLE 0x851E
#endif
#ifndef GL_VERTEX_ARRAY_STORAGE_HINT_APPLE
#  define GL_VERTEX_ARRAY_STORAGE_HINT_APPLE 0x851F
#endif
#ifndef GL_VERTEX_ARRAY_RANGE_POINTER_APPLE
#  define GL_VERTEX_ARRAY_RANGE_POINTER_APPLE 0x8521
#endif
#ifndef GL_STORAGE_CLIENT_APPLE
#  define GL_STORAGE_CLIENT_APPLE 0x85B4
#endif
#ifndef GL_STORAGE_CACHED_APPLE
#  define GL_STORAGE_CACHED_APPLE 0x85BE
#endif
#ifndef GL_STORAGE_SHARED_APPLE
#  define GL_STORAGE_SHARED_APPLE 0x85BF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC) (GLsizei length, GLvoid *pointer);
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
typedef void (APIENTRYP PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC) (GLenum pname, GLint param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexArrayRangeAPPLE
extern PFNGLUXVERTEXARRAYRANGEAPPLEPROC glVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushVertexArrayRangeAPPLE
extern PFNGLUXFLUSHVERTEXARRAYRANGEAPPLEPROC glFlushVertexArrayRangeAPPLE;
#endif
#ifndef __GLUX__GLFCT_glVertexArrayParameteriAPPLE
extern PFNGLUXVERTEXARRAYPARAMETERIAPPLEPROC glVertexArrayParameteriAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
